export const SET_POLICY_DATA = "SET_POLICY_DATA";
export const SET_POLICY_PAGINATION = "SET_POLICY_PAGINATION";
export const SET_REGION_SELECTION = "SET_REGION_SELECTION";
export const SET_IS_POLICY_LOADING = "SET_IS_POLICY_LOADING";
export const SET_POLICY_TIMELINE_DATA = "SET_POLICY_TIMELINE_DATA";
export const SET_POLICY_TIMELINE_DATA_LOADING =
  "SET_POLICY_TIMELINE_DATA_LOADING";
