# Generated by Django 3.2.5 on 2021-11-20 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSegment',
            fields=[
                ('vehicle_segment', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(unique=True)),
                ('date_of_purchase', models.DateField()),
                ('customer_id', models.IntegerField(unique=True)),
                ('premimum', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)])),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('customer_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('customer_income_group', models.CharField(choices=[('0-$25K', '0-$25K'), ('$25-$70K', '$25-$70K'), ('>$70K', '>$70K')], max_length=10)),
                ('customer_marital_status', models.BooleanField(default=False)),
                ('customer_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.region')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_vehicle_fuel', to='policy.fuel')),
                ('vehicle_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_vehicle_segment', to='policy.vehiclesegment')),
            ],
        ),
    ]
